import type { LucideIcon } from "lucide-react";

import {
  ArrowUpRight,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleHelp,
  Clipboard,
  Copy,
  Eye,
  EyeOff,
  Droplet,
  Info,
  Link,
  Maximize2,
  Minus,
  Minimize2,
  Monitor,
  Moon,
  Plus,
  RefreshCw,
  Search,
  ShieldCheck,
  Sparkles,
  Sun,
  TriangleAlert,
  User,
  X,
} from "lucide-react";

export const iconLibrary: Record<string, LucideIcon> = {
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  refresh: RefreshCw,
  light: Sun,
  dark: Moon,
  help: CircleHelp,
  info: Info,
  warning: TriangleAlert,
  danger: CircleAlert,
  checkbox: Check,
  check: CheckCircle,
  copy: Copy,
  eyeDropper: Droplet,
  clipboard: Clipboard,
  person: User,
  close: X,
  openLink: Link,
  arrowUpRight: ArrowUpRight,
  minus: Minus,
  plus: Plus,
  calendar: Calendar,
  eye: Eye,
  eyeOff: EyeOff,
  search: Search,
  security: ShieldCheck,
  sparkle: Sparkles,
  computer: Monitor,
  minimize: Minimize2,
  maximize: Maximize2,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
